# Generated by Django 3.1.3 on 2020-11-02 15:34

from django.db import migrations, models
import django.db.models.deletion
import myapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=myapi.models.upload_to)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.target')),
            ],
        ),
    ]
